In [2]:
import tensorflow as tf
tf.__version__
tf.get_default_graph() # 기본 그래프 정보를 출력하는 함수

In [ ]:
with tf.Session() as sess:
    print(sess.run(x))

In [ ]:
with tf.Session(graph=testGraph) as sess:
    print(sess.run(x))

In [ ]:
# 아래처럼 변수에 대한 직접적으로 접근을 할 수도 있다.
sess = tf.InteractiveSession()
x.eval()
y.eval()

In [ ]:
"hihell" # 입력
"ihello" # 출력

In [ ]:
# time_step: 6, # input_dim: 5(전체 vocabulary의 크기), hidden_size: 5(출력의 크기)

In [ ]:
idx2char = sorted(list(set('hihello')))
# for i, ch in enumerate(idx2char):
xdata = [[0, 1, 0, 2, 3, 3]]
ydata = [[1, 0, 2, 3, 3, 4]] # ihello
num_classes = 5
input_dim = 5
hidden_size = 5
batch_size = 1
sequence_length = 6
learning_rate = 0.1

x = tf.placeholder(tf.float32, [None, sequence_length, input_dim])
y = tf.placeholder(tf.float32, [None, sequence_length])

cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

cell.zero_state() # 이 정도는 고정된 코드들입니다.
ini_state = cell.zero_state(batch_size, tf.float32) # 고정된 코드. 웬만하면 이렇게 사용됨
tf.nn.dynamic_rnn(cell, x, initial_state=ini_state, dtype=tf.float32)

weights = tf.ones([batch_size, sequence_length])
tf.contrib.seq2seq.sequence_loss(logits=, targets=y, weights=weights) # 셀에서 출력되는 값이 logit임. 실제 출력 값은 target임.
loss = tf.reduce_mean(sequence_loss)

In [ ]:
d = {}
l = list('hihell')
for i, c in enumerate(idx2char):
    d[c] = i
list(map(lambda x: d[x], l))

In [71]:
import numpy as np
from tensorflow.contrib import rnn
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()
tf.reset_default_graph()

In [56]:
h, e, l, o = [[0 for _ in range(4)] for _ in range(4)]

In [63]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [57]:
h

[0, 0, 0, 0]

In [58]:
h[0] = 1
e[1] = 1
l[2] = 1
o[3] = 1

In [59]:
h

[1, 0, 0, 0]

In [44]:
with tf.variable_scope('first_cell') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    xdata = np.array([[0, 1, 0, 0]], dtype=tf.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, xdata, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2


TypeError: data type not understood

In [72]:
with tf.variable_scope('sec_cell') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    xdata = np.array([[h, e, l, l, o]], dtype=np.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, xdata, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

ValueError: Fetch argument <tf.Operation 'sec_cell/init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "sec_cell/init"
op: "NoOp"
input: "^sec_cell/rnn/basic_rnn_cell/kernel/Assign"
input: "^sec_cell/rnn/basic_rnn_cell/bias/Assign"
 is not an element of this graph.)

In [ ]:
with tf.variable_scope('sec_cell') as scope:
    hidden_size = 2
    batch_size = 3
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    xdata = np.array([[h, e, l, l, o]], dtype=np.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, xdata, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())
    init_state = cell.zero_state(batch_size, tf.float32)

In [73]:
batch_size = 3
seq_len = 5
in_dim = 3
xdata = np.arange(45).reshape(batch_size, seq_len, in_dim)
print(xdata)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [ ]:
with tf.variable_scope('multi_rnn_cell') as scope:
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=5)
    cell = tf.contrib.rnn.MultiRNNCell([cell]*3)
    outputs, _states = tf.nn.dynamic_rnn(cell, xdata)
    sess.run(tf.global_variables_initializer())
    pp.print(outputs.eval())

In [74]:
ydata = tf.constant([[1,1,1]])
prediction1 = tf.constant([[[0.3, 0.7],
                           [0.1, 0.9],
                           [0.3, 0.7]]])
prediction2 = tf.constant([[[0.4, 0.6],
                           [0.4, 0.6],
                           [0.6, 0.4]]])
loss1 = tf.contrib.seq2seq.sequence_loss(prediction1, ydata)
sess.run(tf.global_variables_initializer())
loss1.eval()

TypeError: sequence_loss() missing 1 required positional argument: 'weights'