print("hello")

설명글
## 반갑습니다
### 안녕하세요
#### 파이썬

In [3]:
import numpy as np

In [4]:
x=np.arange(1,10001)
x2=np.arange(10001,20001)

In [6]:
%%time
x3=np.zeros_like(x)
for i in range(10000):
    x3[i]=x[i]+x2[i]

Wall time: 15.5 ms


In [8]:
%%time
x3=x+x2

Wall time: 0 ns


In [10]:
np.exp(2)

7.38905609893065

In [13]:
x=np.array([4,5,6,7])
print(x.argmin())
print(x.argmax())

0
3


In [14]:
x=np.array([[1,2], [3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
x.sum()
x.sum(axis=0)
x.sum(axis=1)

array([ 3,  7, 11])

In [21]:
x=np.array([[11,2], [23,14],[5,26]])
print(np.sort(x)) #axis=1
print("*"*50)
print(np.sort(x,axis=0))

[[ 2 11]
 [14 23]
 [ 5 26]]
**************************************************
[[ 5  2]
 [11 14]
 [23 26]]


In [22]:
x

array([[11,  2],
       [23, 14],
       [ 5, 26]])

In [23]:
x=np.array([40,30,10,20])
np.argsort(x)
#  0  1  2  3       2  3  1  0               
#[40,30,10,20] => [10,20,30,40]

array([2, 3, 1, 0], dtype=int64)