1. 이터레이터(iterator)
-데이터를 차례대로 꺼낼 수 있도록 해주는 객체
for i in range(100):
2. 반복 가능한 객체(iterable):리스트,셋,딕셔너리,문자열...

In [3]:
dir([1,2,3])
it=[1,2,3].__iter__()

In [4]:
it.__next__()

1

In [5]:
it.__next__()

2

In [6]:
it.__next__()

3

In [7]:
it=range(3).__iter__()
it.__next__()
#for i in range(3):

0

In [10]:
# class 이터레이터명:
#     def __iter__(self):
#         코드
#     def __next__(self):
#         코드
        

class Counter:
    def __init__(self, stop):#0번,1번,2번 붕어빵 만드는게 목표
        self.cur=0  #현재 붕어빵 번호
        self.stop=stop #붕어빵 굽기 종료 시점
    def __iter__(self):
        return self 
    def __next__(self):
        if self.cur<self.stop:
            r=self.cur
            self.cur+=1
            return r
        else:
            raise StopIteration        
#붕어빵기계(클래스), 붕어빵(객체)
for i in Counter(3):#붕어빵기계(붕어빵3마리)
    print(i) #0 1 2

0
1
2


In [14]:
a,_,c=Counter(3)
c

2

2. 제너레이터 : 이터레이터를 생성해주는 함수
- yield 키워드 사용하여 생성.

In [16]:
def num_gen(): #제너레이터
    yield 1
    yield 2
    yield 3   
for i in num_gen():
    print(i) #1 2 3 출력
    

1
2
3


In [20]:
# 변수=next(제너레이터 객체)
g=num_gen()
next(g)
next(g)
next(g)

3

In [21]:
def myGen():
    i=0
    while True:
        i+=1
        yield i

In [22]:
for i in myGen():
    print(i)
    if i>5:
        break

1
2
3
4
5
6


In [ ]:
1.문제 정의
-다중 분류, 입력:도형이미지, 출력:각 도형 확률
2.데이터 수집(데이터부족->데이터생성)
-케라스는 ImageDataGenerator사용해서 데이터 증식,이미지파일 학습
3. 모델 생성
4. 학습
5. 평가

In [25]:
import numpy as np
from keras.models import Sequential
from keras.layers import *
from keras.layers.convolutional import *
from keras.preprocessing.image import ImageDataGenerator

In [36]:
#https://keras.io/preprocessing/image/#imagedatagenerator-methods
train_datagen=ImageDataGenerator(rescale=1./255)
test_datagen=ImageDataGenerator(rescale=1./255)

In [37]:
train_gen=train_datagen.flow_from_directory(
'hand/train',
target_size=(24,24),
class_mode='categorical',
batch_size=3
)

test_gen=test_datagen.flow_from_directory(
'hand/test',
target_size=(24,24),
class_mode='categorical',
batch_size=3
)



Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [34]:
type(train_gen)
for x, y in train_gen:
    print(x)
    print("="*50)
    print(y)
    print("="*50)
    print(x.shape)
    print("="*50)
    print(y.shape)
    break

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1

#모델 생성
1. conv layer:입력(24,24), 채널(3), 필터(3,3), 필터개수(32), 활성화(relu)
2. pooling : 크기(2,2)
3. flatten
4. dense : 출력(128), 활성화(relu)
5. dense : 출력(3), 활성화(softmax)

In [45]:
model=Sequential()
model.add(Conv2D(32, kernel_size=(3,3),
                activation='relu',
                input_shape=(24,24,3)))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 22, 22, 32)        896       
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 20, 20, 64)        18496     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 10, 10, 64)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               819328    
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 387       
Total params: 839,107
Trainable params: 839,107
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

W0820 11:55:46.035514  4628 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0820 11:55:46.056457  4628 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [47]:
#fit : 케라스 모델 학습 함수
#fit_generator:제너레이터로 생성된 데이터를 학습 함수

In [50]:
model.fit_generator(
train_gen,
steps_per_epoch=15,  #1에폭:45개, 배치:3 이므로 15=45/3
epochs=100,
validation_data=test_gen,
validation_steps=5
)

W0820 12:04:48.219012  4628 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0820 12:04:48.288825  4628 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
15/15 [==============================] - 1s 47ms/step - loss: 0.9590 - acc: 0.6222 - val_loss: 0.5904 - val_acc: 0.6667
Epoch 2/100
15/15 [==============================] - 0s 18ms/step - loss: 0.2679 - acc: 0.8667 - val_loss: 0.1845 - val_acc: 1.0000
Epoch 3/100
15/15 [==============================] - 0s 21ms/step - loss: 0.0605 - acc: 0.9778 - val_loss: 0.0345 - val_acc: 1.0000
Epoch 4/100
15/15 [==============================] - 0s 20ms/step - loss: 0.0242 - acc: 1.0000 - val_loss: 0.0273 - val_acc: 1.0000
Epoch 5/100
15/15 [==============================] - 0s 19ms/step - loss: 0.0023 - acc: 1.0000 - val_loss: 0.0114 - val_acc: 1.0000
Epoch 6/100
15/15 [==============================] - 0s 21ms/step - loss: 0.0023 - acc: 1.0000 - val_loss: 0.0086 - val_acc: 1.0000
Epoch 7/100
15/15 [==============================] - 0s 21ms/step - loss: 7.4997e-04 - acc: 1.0000 - val_loss: 0.0094 - val_acc: 1.0000
Epoch 8/100
15/15 [==============================] - 0s 21ms/step - loss

Epoch 61/100
15/15 [==============================] - 0s 21ms/step - loss: 5.3459e-06 - acc: 1.0000 - val_loss: 0.0195 - val_acc: 1.0000
Epoch 62/100
15/15 [==============================] - 0s 20ms/step - loss: 5.1486e-06 - acc: 1.0000 - val_loss: 0.0195 - val_acc: 1.0000
Epoch 63/100
15/15 [==============================] - 0s 20ms/step - loss: 4.9009e-06 - acc: 1.0000 - val_loss: 0.0200 - val_acc: 1.0000
Epoch 64/100
15/15 [==============================] - 0s 18ms/step - loss: 4.7168e-06 - acc: 1.0000 - val_loss: 0.0203 - val_acc: 1.0000
Epoch 65/100
15/15 [==============================] - 0s 19ms/step - loss: 4.4916e-06 - acc: 1.0000 - val_loss: 0.0210 - val_acc: 1.0000
Epoch 66/100
15/15 [==============================] - 0s 19ms/step - loss: 4.3048e-06 - acc: 1.0000 - val_loss: 0.0213 - val_acc: 1.0000
Epoch 67/100
15/15 [==============================] - 0s 19ms/step - loss: 4.1379e-06 - acc: 1.0000 - val_loss: 0.0216 - val_acc: 1.0000
Epoch 68/100
15/15 [=====================

In [55]:
#모델 평가 : evalute_generator
scores=model.evaluate_generator(test_gen, steps=5)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

acc: 100.00%


In [57]:
#예측 결과를 클래스 벡터로 표현
output=model.predict_generator(test_gen,steps=5)
np.set_printoptions(
    formatter={'float': lambda x: "{0:0.3f}".
               format(x)})
print(test_gen.class_indices)
print(output)

{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[1.000 0.000 0.000]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [1.000 0.000 0.000]
 [0.997 0.000 0.003]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]]


In [60]:
from keras.preprocessing.image 
import ImageDataGenerator, array_to_img, img_to_array, load_img
#from keras.preprocessing import image

SyntaxError: invalid syntax (<ipython-input-60-e3b915524919>, line 1)

In [83]:
data_aug_gen=ImageDataGenerator(
rescale=1./255,
rotation_range=90,
    width_shift_range=1,
    height_shift_range=90,
    zoom_range=[0.2,3.0],#원본이미지80%~120%크기
    fill_mode='nearest',
    vertical_flip=True,
    shear_range=0.1
)

In [88]:
# img=load_img('dog.6415.jpg')
# img

In [85]:
x=img_to_array(img)
#p.shape(img)#(24, 24, 3)
x=x.reshape((1,)+x.shape)
np.shape(x) #(1, 24, 24, 3)

(1, 396, 345, 3)

In [86]:
#가짜 이미지 50개 생성

In [87]:
i=0
for data in data_aug_gen.flow(x, batch_size=1, 
                           save_to_dir='hand',
                           save_format='jpg', 
                           save_prefix='sample'):
    i+=1
    if i>50:
        break